// <auto-generated />
using System;
using LectureAgent.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LectureAgent.Infrastructure.Migrations
{
    [DbContext(typeof(LectureContext))]
    partial class LectureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LectureAgent.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<string>("AuditEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CloudSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncedToCloud")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditEntryId");

                    b.HasIndex("SyncedToCloud")
                        .HasDatabaseName("IX_Audit_Synced");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_Audit_Entity");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LectureAgent.Domain.Entities.ConfigEntry", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverridable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigKey");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("LectureAgent.Domain.Entities.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<int>("OnlineStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordingFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("OrganizationId", "CenterId", "RoomId")
                        .IsUnique()
                        .HasDatabaseName("IX_Device_Org_Center_Room");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("LectureAgent.Domain.Entities.LectureSession", b =>
                {
                    b.Property<string>("LectureSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectedDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveFolderPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrivePdfFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveVideoFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastStatusChange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchingReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFileLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PdfFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("QcPassedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QcResults")
                        .HasColumnType("TEXT");

                    b.Property<int>("QcStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledEndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduledSlotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFileLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("VideoFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YouTubeFailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("YouTubePublishStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("YouTubePublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("LectureSessionId");

                    b.HasIndex("MatchStatus")
                        .HasDatabaseName("IX_Lecture_MatchStatus");

                    b.HasIndex("QcStatus")
                        .HasDatabaseName("IX_Lecture_QcStatus");

                    b.HasIndex("ReviewStatus")
                        .HasDatabaseName("IX_Lecture_ReviewStatus");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Lecture_Status");

                    b.HasIndex("YouTubePublishStatus")
                        .HasDatabaseName("IX_Lecture_YouTubePublishStatus");

                    b.HasIndex("CenterId", "DetectedStartTime")
                        .HasDatabaseName("IX_Lecture_Center_Date");

                    b.HasIndex("OrganizationId", "CenterId", "Status")
                        .HasDatabaseName("IX_Lecture_Tenant_Status");

                    b.ToTable("LectureSessions");
                });

            modelBuilder.Entity("LectureAgent.Domain.Entities.TimetableEntry", b =>
                {
                    b.Property<string>("TimetableEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("SlotEndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("SlotStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TimetableEntryId");

                    b.HasIndex("CenterId", "ScheduledDate")
                        .HasDatabaseName("IX_Timetable_Center_Date");

                    b.HasIndex("RoomId", "ScheduledDate")
                        .HasDatabaseName("IX_Timetable_Room_Date");

                    b.HasIndex("OrganizationId", "CenterId", "RoomId", "ScheduledDate")
                        .HasDatabaseName("IX_Timetable_Tenant_Room_Date");

                    b.ToTable("TimetableEntries");
                });

            modelBuilder.Entity("LectureAgent.Domain.Entities.TimetableOverride", b =>
                {
                    b.Property<string>("OverrideId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewBatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewRoomId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("NewSlotEndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewSlotId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("NewSlotStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewSubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewTeacherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OriginalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSlotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTimetableEntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverrideType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OverrideId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Override_Active");

                    b.HasIndex("CenterId", "EffectiveDate")
                        .HasDatabaseName("IX_Override_Center_Date");

                    b.ToTable("TimetableOverrides");
                });

            modelBuilder.Entity("LectureAgent.Domain.Entities.UploadQueueEntry", b =>
                {
                    b.Property<string>("QueueEntryId")
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesUploaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveFolderPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveResumableUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LectureSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("QueueEntryId");

                    b.HasIndex("LectureSessionId")
                        .HasDatabaseName("IX_Queue_LectureId");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("IX_Queue_Status_RetryTime");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("IX_Queue_Status_Updated");

                    b.ToTable("UploadQueues");
                });
#pragma warning restore 612, 618
        }
    }
}
